import { realtimeMiddleware } from "@inngest/realtime/middleware";
import { EventSchemas, Inngest } from "inngest";
import {
  candidateWelcomeBatchDataSchema,
  candidateWelcomeDataSchema,
  collectChatIdsDataSchema,
  interviewAnalysisDataSchema,
  interviewCompleteDataSchema,
  interviewSendQuestionDataSchema,
  parseMissingContactsDataSchema,
  parseNewResumesDataSchema,
  refreshSingleResumeDataSchema,
  responseScreenDataSchema,
  screenAllResponsesDataSchema,
  screenNewResponsesDataSchema,
  screenResponsesBatchDataSchema,
  telegramAuthErrorDataSchema,
  telegramMessageSendDataSchema,
  vacancyRequirementsExtractDataSchema,
  vacancyResponsesRefreshDataSchema,
  vacancyUpdateActiveDataSchema,
  vacancyUpdateSingleDataSchema,
  verifyHHIntegrationDataSchema,
  voiceTranscriptionDataSchema,
} from "./types";

// Create Inngest client with Zod schemas for type-safe events
export const inngest = new Inngest({
  id: "selectio",
  name: "Selectio Jobs",
  middleware: [realtimeMiddleware()],
  schemas: new EventSchemas().fromSchema({
    "vacancy/requirements.extract": vacancyRequirementsExtractDataSchema,
    "response/screen": responseScreenDataSchema,
    "response/screen.new": screenNewResponsesDataSchema,
    "response/screen.all": screenAllResponsesDataSchema,
    "response/screen.batch": screenResponsesBatchDataSchema,
    "response/resume.parse-new": parseNewResumesDataSchema,
    "response/resume.refresh": refreshSingleResumeDataSchema,
    "response/contacts.parse-missing": parseMissingContactsDataSchema,
    "vacancy/update.active": vacancyUpdateActiveDataSchema,
    "vacancy/update.single": vacancyUpdateSingleDataSchema,
    "vacancy/responses.refresh": vacancyResponsesRefreshDataSchema,
    "vacancy/chat-ids.collect": collectChatIdsDataSchema,
    "candidate/welcome": candidateWelcomeDataSchema,
    "candidate/welcome.batch": candidateWelcomeBatchDataSchema,
    "telegram/message.send": telegramMessageSendDataSchema,
    "telegram/voice.transcribe": voiceTranscriptionDataSchema,
    "telegram/interview.analyze": interviewAnalysisDataSchema,
    "telegram/interview.send-question": interviewSendQuestionDataSchema,
    "telegram/interview.complete": interviewCompleteDataSchema,
    "telegram/auth.error": telegramAuthErrorDataSchema,
    "integration/hh.verify": verifyHHIntegrationDataSchema,
  }),
});
